/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testNftSol from "./TestNFT.sol";
export type { testNftSol };
export type { Storage } from "./Storage";
