/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Storage, StorageInterface } from "../Storage";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "StoreEvent",
    type: "event",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a3806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b604051610050919061011b565b60405180910390f35b610073600480360381019061006e9190610167565b61007e565b005b60008054905090565b606481106100c1576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100b8906101f1565b60405180910390fd5b7ff968ef841feb103aafe6a7faf747366409c985dbe99998d2ab7ecd867096542c336040516100f09190610252565b60405180910390a18060008190555050565b6000819050919050565b61011581610102565b82525050565b6000602082019050610130600083018461010c565b92915050565b600080fd5b61014481610102565b811461014f57600080fd5b50565b6000813590506101618161013b565b92915050565b60006020828403121561017d5761017c610136565b5b600061018b84828501610152565b91505092915050565b600082825260208201905092915050565b7f4e756d626572206d757374206265203c20313030000000000000000000000000600082015250565b60006101db601483610194565b91506101e6826101a5565b602082019050919050565b6000602082019050818103600083015261020a816101ce565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061023c82610211565b9050919050565b61024c81610231565b82525050565b60006020820190506102676000830184610243565b9291505056fea264697066735822122073842f7e06ecc7b3c284d86a6619dabf224a84602f6aca160b5b8f79998d258c64736f6c63430008120033";

type StorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Storage__factory extends ContractFactory {
  constructor(...args: StorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Storage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Storage__factory {
    return super.connect(runner) as Storage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StorageInterface {
    return new Interface(_abi) as StorageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Storage {
    return new Contract(address, _abi, runner) as unknown as Storage;
  }
}
