/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Storage, StorageInterface } from "../../contracts/Storage";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "StoreEvent",
    type: "event",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b5061028d8061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c80632e64cec1146100385780636057361d14610056575b5f80fd5b610040610072565b60405161004d9190610115565b60405180910390f35b610070600480360381019061006b919061015c565b61007a565b005b5f8054905090565b606481106100bd576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100b4906101e1565b60405180910390fd5b7ff968ef841feb103aafe6a7faf747366409c985dbe99998d2ab7ecd867096542c336040516100ec919061023e565b60405180910390a1805f8190555050565b5f819050919050565b61010f816100fd565b82525050565b5f6020820190506101285f830184610106565b92915050565b5f80fd5b61013b816100fd565b8114610145575f80fd5b50565b5f8135905061015681610132565b92915050565b5f602082840312156101715761017061012e565b5b5f61017e84828501610148565b91505092915050565b5f82825260208201905092915050565b7f4e756d626572206d757374206265203c203130300000000000000000000000005f82015250565b5f6101cb601483610187565b91506101d682610197565b602082019050919050565b5f6020820190508181035f8301526101f8816101bf565b9050919050565b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f610228826101ff565b9050919050565b6102388161021e565b82525050565b5f6020820190506102515f83018461022f565b9291505056fea2646970667358221220fe95b2e99d528c59d7bcf7e93a78a919d30749d06efaedacf9471184932d03c664736f6c63430008140033";

type StorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Storage__factory extends ContractFactory {
  constructor(...args: StorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Storage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Storage__factory {
    return super.connect(runner) as Storage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StorageInterface {
    return new Interface(_abi) as StorageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Storage {
    return new Contract(address, _abi, runner) as unknown as Storage;
  }
}
