/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MetaOperatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "Carboncredits"
      | "DAPPAccount"
      | "NGOAccount"
      | "approveTokens"
      | "balanceOfCertificateNFT"
      | "balanceOfTokens"
      | "buyCarbonCredits"
      | "canSponsorTransactionFor"
      | "certificatesAndScoresOfCertificateOwner"
      | "disburseTokens"
      | "getCertificateScore"
      | "getTreeLevel"
      | "levelUpTree"
      | "mintCertificate"
      | "mintTree"
      | "rewardTokens"
      | "tokensAndLevelsOfTreeOwner"
      | "transferTokens"
      | "transferTokensFrom"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "Carboncredits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DAPPAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NGOAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfCertificateNFT",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyCarbonCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canSponsorTransactionFor",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificatesAndScoresOfCertificateOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disburseTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreeLevel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "levelUpTree",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCertificate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintTree",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensAndLevelsOfTreeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokensFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "Carboncredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DAPPAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "NGOAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfCertificateNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyCarbonCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canSponsorTransactionFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificatesAndScoresOfCertificateOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disburseTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levelUpTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensAndLevelsOfTreeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokensFrom",
    data: BytesLike
  ): Result;
}

export interface MetaOperator extends BaseContract {
  connect(runner?: ContractRunner | null): MetaOperator;
  waitForDeployment(): Promise<this>;

  interface: MetaOperatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Carboncredits: TypedContractMethod<[], [string], "view">;

  DAPPAccount: TypedContractMethod<[], [string], "view">;

  NGOAccount: TypedContractMethod<[], [string], "view">;

  approveTokens: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOfCertificateNFT: TypedContractMethod<
    [certOwner: AddressLike],
    [bigint],
    "view"
  >;

  balanceOfTokens: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  buyCarbonCredits: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  canSponsorTransactionFor: TypedContractMethod<
    [_origin: AddressLike, _to: AddressLike, _data: BytesLike],
    [boolean],
    "view"
  >;

  certificatesAndScoresOfCertificateOwner: TypedContractMethod<
    [certOwner: AddressLike],
    [[bigint[], bigint[]]],
    "view"
  >;

  disburseTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCertificateScore: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getTreeLevel: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  levelUpTree: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintCertificate: TypedContractMethod<
    [to: AddressLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintTree: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  rewardTokens: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokensAndLevelsOfTreeOwner: TypedContractMethod<
    [treeOwner: AddressLike],
    [[bigint[], bigint[]]],
    "view"
  >;

  transferTokens: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferTokensFrom: TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Carboncredits"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAPPAccount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NGOAccount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveTokens"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOfCertificateNFT"
  ): TypedContractMethod<[certOwner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfTokens"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyCarbonCredits"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canSponsorTransactionFor"
  ): TypedContractMethod<
    [_origin: AddressLike, _to: AddressLike, _data: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "certificatesAndScoresOfCertificateOwner"
  ): TypedContractMethod<
    [certOwner: AddressLike],
    [[bigint[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "disburseTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCertificateScore"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTreeLevel"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "levelUpTree"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintCertificate"
  ): TypedContractMethod<
    [to: AddressLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintTree"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardTokens"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokensAndLevelsOfTreeOwner"
  ): TypedContractMethod<
    [treeOwner: AddressLike],
    [[bigint[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferTokens"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferTokensFrom"
  ): TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
